repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
  - repo: local
    hooks:
      - id: cargo-fmt
        name: Format Rust
        description: Reformat Rust code as needed
        entry: bash -c 'cd rust && cargo fmt'
        language: system
        pass_filenames: false
