# We could configure ruff in python/,
# but there is also python code outside the python directory,
# so this config belongs at the top level.

exclude = [
    ".git",
    # suggested virtualenv for python/
    ".venv-dev",
    # suggested virtualenv for docs/
    ".venv-docs",
    # suggested virtualenv for tools/
    ".venv-tools",
]


lint.ignore = [
"B006", # Do not use mutable data structures for argument defaults
"B008", # Do not perform function call `AIM` in argument defaults; instead, perform the call within the function, or read the default from a module-level singleton variable
"B015", # Pointless comparison. Did you mean to assign a value? Otherwise, prepend `assert` or remove it.
"B016", # Cannot raise a literal. Did you intend to return it or raise an Exception?
"B017", # Do not assert blind exception: `Exception`
"B018", # Found useless ... Either assign it to a variable or remove it.
"B023", # Function definition does not bind loop variable `...`
"BLE001", # Do not catch blind exception: `Exception`
"C400", # Unnecessary generator (rewrite as a list comprehension)
"C401", # Unnecessary generator (rewrite as a set comprehension)
"C405", # Unnecessary list literal (rewrite as a set literal)
"C408", # Unnecessary `...()` call (rewrite as a literal)
"C417", # Unnecessary `map()` usage (rewrite using a list comprehension)
"D419", # Docstring is empty
"DTZ001", # `datetime.datetime()` called without a `tzinfo` argument
"DTZ005", # `datetime.datetime.now()` called without a `tz` argument
"DTZ007", # Naive datetime constructed using `datetime.datetime.strptime()` without %z
"DTZ011", # `datetime.date.today()` used
"EXE001", # Shebang is present but file is not executable
"EXE002", # The file is executable but no shebang is present
"F401", # `...` imported but unused
"F821", # Undefined name `...`
"FLY002", # Consider `f"{version_cmd}&&{sphinx_apidoc_cmd}"` instead of string join
"N999", # Invalid module name: 'test_np_xTx'
"PIE810", # Call `startswith` once with a `tuple`
"PLW1510", # `subprocess.run` without explicit `check` argument
"PT031", # `pytest.warns()` block should contain a single simple statement
"PYI061", # Use `Literal[...] | None` rather than `Literal[None, ...]`
"RUF012", # Mutable default value for class attribute
"RUF046", # Value being cast to `int` is already an integer
"RUF059", # Unpacked variable `sources` is never used
"S110", # `try`-`except`-`pass` detected, consider logging the exception
"SIM102", # Use a single `if` statement instead of nested `if` statements
"SIM115", # Use a context manager for opening files
"SIM201", # Use `left != Bound(by=[pl.col.B], per_group=10)` instead of `not left == Bound(by=[pl.col.B], per_group=10)`
"SIM201", # Use `left != str(right)` instead of `not left == str(right)`
"SIM201", # Use `version_date != date.strftime("%Y%m%d")` instead of `not version_date == date.strftime("%Y%m%d")`
"TRY002", # Create your own exception
"TRY004", # Prefer `TypeError` exception for invalid type
"TRY201", # Use `raise` without specifying exception name
"UP030", # Use implicit references for positional format fields
"UP031", # Use format specifiers instead of percent format
]
