repos:
# TODO: Bulk reformat, and then enable.
# - repo: https://github.com/pre-commit/pre-commit-hooks
#   rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
#   hooks:
#     - id: trailing-whitespace
#     - id: end-of-file-fixer
#     - id: check-yaml
#     - id: check-added-large-files
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: cb8c523fd4835aba42af70f4cad5568db4df0b6c  # frozen: v0.16.0
  hooks:
    - id: ruff-check
    - id: ruff-format
      args: ['--diff'] # or '--check' for just an error
