# This keeps the tracking branches latest and stable in sync with their targets:
# * Whenever there's a push to main, it updates latest to match.
# * Whenever there's a release, it updates stable to match.

name: Sync Branches

on:
  push:
    branches: [main]
  release:
    types: [published]

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update latest
        if: ${{ github.ref == 'refs/heads/main' }}
        run: git branch -f latest ${{ github.ref }}

      - name: Update stable
        # TODO: Fix this logic to fire only if this is highest semantic version.
        # Can probably do this just by hard-wiring the major number.
        if: ${{ startsWith(github.ref, 'refs/tags/v') && ! contains(github.ref, '-rc.') }}
        run: git branch -f stable ${{ github.ref }}
